language: node_js

sudo: required
dist: trusty

os:
  - linux
  - osx

branches:
  only:
  - master

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache
  - $HOME/.npm

addons:
  apt:
    packages:
      - graphicsmagick
      - libgnome-keyring-dev
      - icnsutils

node_js:
  - "8"

env:
  global:
    - secure: "d9TTcG49QBDePFSGPEkZwJt32Yo6VJb0/pY+RU37FPG+E4zKvUBlOzi3PxFV+nhoAUCCFz4l8ZZLQYxpUTvl4ABIDsKVMqkAAaDOOnUn0JuS8A8BAUnrJwIX2s34dQCHqqGuCg1DQySw0Cy9Y9ZQDyE1C4DjcLwo3tuqKmHFJhlOazGYrG0XmgD9ldvg0i8UEzXRkXPSP7MEWNLSYVXpLerP+0ESMqhSuHLuQ/C7KkYPEg/rIcKi6K980vUY0ujxDMzmKpOU/g7XIyd/YrUHzNwljjSZdU9m4WIrBnWDjA3m2JIFNovxsuOs5/qSAJ+UMHfnhB8fzavIikvkOEWOxddeNC/9zpNYuIEWGl6Y8JjXIQVrMP6ijU5pgvVUjvqWuHK/mJEXbRYwSylbHNciyHcoP9bwX+FIcphYF/HzNYYksrLXOzrazlRYktFTOQGEEcoKkIPXRcl7IANm/V8repFzFHtqI11bzEqojSYlWJ950SD8E2i3wjEkpSVvBgsBv2Jt6o2eJijdhxVeA187MiFfcxqkeTgJJysD9q3KcEF+MOoX1fPT03BzwK3YtwuOmqZU6R1xx60cdEHMYI2RvLBJS2/WIMFtJrfVW8ryl7GrohRWTCPStfy8CRiOMohu9AylVh0IlLd46zxQkSyCBv4X+WiUXUd+OcyNRyFJWJA="

install:
    - npm install

script:
    - npm run release
