platform:
  - x64

branches:
  only:
    - master

environment:
  GH_TOKEN:
    secure: pBC9MniqBLQ3ejxutDYFGYeIU13oDK7pFfqiQf+IWCIOkMdB0ystwFLIx7tJ/fRV

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%LOCALAPPDATA%\bower'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run release

test: off
